# Generated by Django 6.0.4 on 2026-04-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('building_location', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
